---
- name: "Creating a user-prometheus"
  user:
    name: prometheus
    shell: /sbin/false

- name: "Download prometheus the tar file url"
  get_url:
    url: "{{ prometheus_url }}"
    dest: /tmp/

- name: "Unarchive the downloaded file"
  unarchive:
    src: "/tmp/prometheus-{{ version }}.tar.gz"
    dest: /tmp/
    remote_src: true

- name: "Creating 2 directories"
  file:
    path : " {{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: "Moving extracted files to a folder"
  copy:
    remote_src: yes
    src: /tmp/prometheus-{{ version }}/
    dest: /var/lib/prometheus/
    owner: prometheus
    group: prometheus

- name: "Copy the prometheus folder to the path /usr/local/bin"
  copy:
    src: "/tmp/prometheus-{{ version }}/prometheus"
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: true

- name: "Copy the promtool folder to the path /usr/local/bin"
  copy:
    src: "/tmp/prometheus-{{ version }}/promtool"
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: true

- name: "Copy the prometheus folder to the path /usr/local/bin"
  copy:
    src: "/tmp/prometheus-{{ version }}/consoles"
    dest: /etc/prometheus/
    owner: prometheus
    group: prometheus
    remote_src: true

- name: "Copy the prometheus folder to the path /usr/local/bin"
  copy:
    src: "/tmp/prometheus-{{ version }}/console_libraries"
    dest: /etc/prometheus/
    owner: prometheus
    group: prometheus
    remote_src: true

- name: "Copy the prometheus.service to /etc/prometheus/"
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: prometheus
    group: prometheus

- name: "Start prometheus service"
  systemd:
    state: started
    name: prometheus
    daemon_reload: yes
    enabled: yes

- name: "Copy the prometheus2.yml to /etc/prometheus/prometheus.yml"
  template:
    src: prometheus2.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: "Start node_exporter service"
  systemd:
    state: restarted
    name: prometheus
